## core
require 'srri/module/kernel'
require 'srri/module/main'
## main
require 'srri/module/audio'
require 'srri/module/graphics'
require 'srri/module/input'
## extended
require 'srri/module/texture_tool'
